<table class="Content">
		<tr>
		  <td>
		    <table class="PagetextContainer">  
          <tr>
            <td>
              <div class="ContentSmallSpacer"></div>
              <div class="p33">
                             
<?php
if (count($this->job) > 0){
    foreach($this->job as $job):
?> 

              <div class="LiveInner Job" id="job_<?= $job["job_id"] ?>">
                  <table class="LiveInnerTable">
                    <tbody><tr>
                      <td class="kl-tl"></td>
	                	  <td class="kl-tc"></td>
                      <td class="kl-tr"></td>
                    </tr>
	                	<tr>
                      <td class="kl-ml"></td>
                      <td class="kl-mc">
                <div class="ItemSeparator"></div>
                <div class="OpenClose"></div>
                <div class="ItemTitle">
                <h2><span><?= $job["job_name"] ?></span></h2>
                </div>
                    <table class="ContentTable">
                          <tr>
                            <td>
                                <?= $job["job_full_text"] ?>
                            </td>
                          </tr>
                        </table>
                      </td>
                      <td class="kl-mr"></td>
                    </tr> 
                    <tr>
                      <td class="kl-bl"></td>
                      <td class="kl-bc"><div class="ItemCommentArrow"></div></td>
                      <td class="kl-br"></td>
                    </tr>
                  </tbody></table>


               </div> 
<?php
    endforeach;
}
else{
    echo("К сожалению на данный момент у нас нет вакансий.");
}
?>
                           
              </div> 
            </td>
          </tr>
        </table>
	   </td>
    </tr>
</table>	


<script type="text/javascript">
    $("div.Job").each(function(){
        var obj = this;
        $(".OpenClose", this).click(function(){
            needOpen = (!$(obj).hasClass("Selected"));
            $(".Selected").removeClass("Selected");
            if (needOpen) $(obj).addClass("Selected");
        });
    });
    
    var host = top.location.toString();
    if (host.indexOf("#") > -1){
        var job_id = host.substring(host.indexOf("#") + 1);        
        $("#job_"+job_id).addClass("Selected");
    }
</script>