<table class="Content">
		<tr>
		  <td>
		    <div class="ContentSmallSpacer"></div>
        <table class="PagetextContainer">
          <tr>
            <td class="p50">
            <h1>Логотипы</h1>
    <div class="Block-logo">
    <p>1. Логотип для партнерских сайтов (<a href="/downloads/*******-logo-partners.ai">скачать .ai</a>)</p>
    <img style="margin-right: 50px" class="float-left" src="/img/logos/3.png" border="0" alt="" width="203" height="74" />
    <img class="float-left" src="/img/logos/4.png" border="0" alt="" width="203" height="74" />
    <div class="clr">&nbsp;</div>

</div>

<div class="Block-logo">
    <p>2. Стандартный логотип (<a href="/downloads/*******-logo-standart.ai">скачать .ai</a>)</p>
    <img style="margin-right: 50px" class="float-left" src="/img/logos/1.png" border="0" alt="" width="198" height="104" />
    <img class="float-left" src="/img/logos/2.png" border="0" alt="" width="198" height="100" />
    <div class="clr">&nbsp;</div>
</div>

<div class="Block-logo">

    <p>3. *******-знак (<a href="/downloads/*******-logo-sign.ai">скачать .ai</a>)</p>
    <img style="margin-right: 136px" class="float-left" src="/img/logos/5.png" border="0" alt="" width="93" height="145" />
    <img class="float-left" src="/img/logos/6.png" border="0" alt="" width="93" height="145" />
    <div class="clr">&nbsp;</div>
</div>

<div class="Block-logo">
    <p>4. Стандартный логотип без подписи (<a href="/downloads/*******-logo-unsigned.ai">скачать .ai</a>)</p>

    <img style="margin-right: 50px" class="float-left" src="/img/logos/7.png" border="0" alt="" width="197" height="101" />
    <img class="float-left" src="/img/logos/8.png" border="0" alt="" width="196" height="101" />
    <div class="clr">&nbsp;</div>
</div>

<div class="Block-logo">
    <p>5. Логотип без подписи для партнерских сайтов (<a href="/downloads/*******-logo-partners-sign.ai">скачать .ai</a>)</p>
    <img style="margin-right: 50px" class="float-left" src="/img/logos/9.png" border="0" alt="" width="201" height="78" />
    <img class="float-left" src="/img/logos/9_1.png" border="0" alt="" width="201" height="78" />

    <div class="clr">&nbsp;</div>

</div>

<div class="Block-logo">
    <p>6. Кнопки (<a href="/downloads/*******-buttons.ai">скачать .ai</a>)</p>
    <img style="margin-right: 40px;" class="float-left" src="/img/logos/10_1.png" border="0" alt="" width="146" height="67" />
    <img class="float-left" src="/img/logos/10_2.png" border="0" alt="" width="146" height="67" />
    <div class="clr">&nbsp;</div>
    <img style="margin-right: 40px;" class="float-left" src="/img/logos/10_3.png" border="0" alt="" width="146" height="66" />
    <img class="float-left" src="/img/logos/10_4.png" border="0" alt="" width="146" height="66" />
    <div class="clr">&nbsp;</div>
    <img style="margin-right: 40px;" class="float-left" src="/img/logos/10_5.png" border="0" alt="" width="146" height="66" />
    <img class="float-left" src="/img/logos/10_6.png" border="0" alt="" width="146" height="66" />
    <div class="clr">&nbsp;</div>
    <img style="margin-right: 40px" class="float-left" src="/img/logos/10_7.png" border="0" alt="" width="146" height="67" />
    <img class="float-left" src="/img/logos/10_8.png" border="0" alt="" width="146" height="66" />
    <div class="clr">&nbsp;</div>
</div>

<div class="Block-logo">
    <p>7. Любимая кнопка</p>

    <img src="/img/logos/knopka_love.gif" border="0" alt="" width="146" height="67" />

    <div class="clr">&nbsp;</div>
</div>

            </td>
          </tr>
        </table>
		  </td>
    </tr>
	</table>	